const audioLibrary = {
  alphabet: [
    {
      original: 'A',
      translation: 'A',
      diphthong: 'AA',
      audioFile: './audios/alphabet/A.mp3',
    },
    {
      original: 'B',
      translation: 'B',
      diphthong: 'BB',
      audioFile: './audios/alphabet/B.mp3',
    },
    {
      original: 'C',
      translation: 'C',
      diphthong: 'CC',
      audioFile: './audios/alphabet/C.mp3',
    },
    {
      original: 'D',
      translation: 'D',
      diphthong: 'DD',
      audioFile: './audios/alphabet/D.mp3',
    },
    {
      original: 'E',
      translation: 'E',
      diphthong: 'EE',
      audioFile: './audios/alphabet/E.mp3',
    },
    {
      original: 'F',
      translation: 'F',
      diphthong: 'FF',
      audioFile: './audios/alphabet/F.mp3',
    },
    {
      original: 'G',
      translation: 'G',
      diphthong: 'GG',
      audioFile: './audios/alphabet/G.mp3',
    },
    {
      original: 'H',
      translation: 'H',
      diphthong: 'HH',
      audioFile: './audios/alphabet/H.mp3',
    },
    {
      original: 'I',
      translation: 'I',
      diphthong: 'II',
      audioFile: './audios/alphabet/I.mp3',
    },
    {
      original: 'J',
      translation: 'J',
      diphthong: 'JJ',
      audioFile: './audios/alphabet/J.mp3',
    },
    {
      original: 'K',
      translation: 'K',
      diphthong: 'KK',
      audioFile: './audios/alphabet/K.mp3',
    },
    {
      original: 'L',
      translation: 'L',
      diphthong: 'LL',
      audioFile: './audios/alphabet/L.mp3',
    },
    {
      original: 'M',
      translation: 'M',
      diphthong: 'MM',
      audioFile: './audios/alphabet/M.mp3',
    },
    {
      original: 'N',
      translation: 'N',
      diphthong: 'NN',
      audioFile: './audios/alphabet/N.mp3',
    },
    {
      original: 'O',
      translation: 'O',
      diphthong: 'OO',
      audioFile: './audios/alphabet/O.mp3',
    },
    {
      original: 'P',
      translation: 'P',
      diphthong: 'PP',
      audioFile: './audios/alphabet/P.mp3',
    },

    {
      original: 'Q',
      translation: 'Q',
      diphthong: 'QQ',
      audioFile: './audios/alphabet/Q.mp3',
    },
    {
      original: 'R',
      translation: 'R',
      diphthong: 'RR',
      audioFile: './audios/alphabet/R.mp3',
    },
    {
      original: 'S',
      translation: 'S',
      diphthong: 'SS',
      audioFile: './audios/alphabet/S.mp3',
    },
    {
      original: 'T',
      translation: 'T',
      diphthong: 'TT',
      audioFile: './audios/alphabet/T.mp3',
    },
    {
      original: 'U',
      translation: 'U',
      diphthong: 'UU',
      audioFile: './audios/alphabet/U.mp3',
    },
    {
      original: 'V',
      translation: 'V',
      diphthong: 'VV',
      audioFile: './audios/alphabet/V.mp3',
    },
    {
      original: 'W',
      translation: 'W',
      diphthong: 'WW',
      audioFile: './audios/alphabet/W.mp3',
    },
    {
      original: 'X',
      translation: 'X',
      diphthong: 'XX',
      audioFile: './audios/alphabet/X.mp3',
    },
    {
      original: 'Y',
      translation: 'Y',
      diphthong: 'YY',
      audioFile: './audios/alphabet/Y.mp3',
    },
    {
      original: 'Z',
      translation: 'Z',
      diphthong: 'ZZ',
      audioFile: './audios/alphabet/Z.mp3',
    },
  ],
  diphthongs: [
    {
      original: 'ai',
      translation: 'ai',
      diphthong: 'ai',
      audioFile: './audios/diphthongs/ai.mp3',
    },
    {
      original: 'au',
      translation: 'au',
      diphthong: 'au',
      audioFile: './audios/diphthongs/au.mp3',
    },
    {
      original: 'ei',
      translation: 'ei',
      diphthong: 'ei',
      audioFile: './audios/diphthongs/ei.mp3',
    },
    {
      original: 'eu',
      translation: 'eu',
      diphthong: 'eu',
      audioFile: './audios/diphthongs/eu.mp3',
    },
    {
      original: 'ie',
      translation: 'ie',
      diphthong: 'ie',
      audioFile: './audios/diphthongs/ie.mp3',
    },
    {
      original: 'ij',
      translation: 'ij',
      diphthong: 'ij',
      audioFile: './audios/diphthongs/ij.mp3',
    },
    {
      original: 'oe',
      translation: 'oe',
      diphthong: 'oe',
      audioFile: './audios/diphthongs/oe.mp3',
    },
    {
      original: 'ou',
      translation: 'ou',
      diphthong: 'ou',
      audioFile: './audios/diphthongs/ou.mp3',
    },
    {
      original: 'ui',
      translation: 'ui',
      diphthong: 'ui',
      audioFile: './audios/diphthongs/ui.mp3',
    },
    {
      original: 'uu',
      translation: 'uu',
      diphthong: 'uu',
      audioFile: './audios/diphthongs/uu.mp3',
    },
  ],
  diphthongsVocabulary: [
    {
      original: 'mais',
      translation: 'corn',
      diphthong: 'ai',
      audioFile: './audios/diphthongsVocabulary/mais.mp3',
    },
    {
      original: 'laid',
      translation: 'song',
      diphthong: 'ai',
      audioFile: './audios/diphthongsVocabulary/laid.mp3',
    },
    {
      original: 'klaar',
      translation: 'ready',
      diphthong: 'ai',
      audioFile: './audios/diphthongsVocabulary/klaar.mp3',
    },
    {
      original: 'kans',
      translation: 'chance',
      diphthong: 'ai',
      audioFile: './audios/diphthongsVocabulary/kans.mp3',
    },
    {
      original: 'haai',
      translation: 'shark',
      diphthong: 'ai',
      audioFile: './audios/diphthongsVocabulary/haai.mp3',
    },
    {
      original: 'auto',
      translation: 'car',
      diphthong: 'au',
      audioFile: './audios/diphthongsVocabulary/auto.mp3',
    },
    {
      original: 'huis',
      translation: 'house',
      diphthong: 'au',
      audioFile: './audios/diphthongsVocabulary/huis.mp3',
    },
    {
      original: 'goud',
      translation: 'gold',
      diphthong: 'ou',
      audioFile: './audios/diphthongsVocabulary/goud.mp3',
    },
    {
      original: 'blauw',
      translation: 'blue',
      diphthong: 'au',
      audioFile: './audios/diphthongsVocabulary/blauw.mp3',
    },
    {
      original: 'ei',
      translation: 'egg',
      diphthong: 'ei',
      audioFile: './audios/diphthongsVocabulary/ei.mp3',
    },
    {
      original: 'neus',
      translation: 'nose',
      diphthong: 'ei',
      audioFile: './audios/diphthongsVocabulary/neus.mp3',
    },
    {
      original: 'meisje',
      translation: 'girl',
      diphthong: 'ei',
      audioFile: './audios/diphthongsVocabulary/meisje.mp3',
    },
    {
      original: 'reis',
      translation: 'journey',
      diphthong: 'ei',
      audioFile: './audios/diphthongsVocabulary/reis.mp3',
    },
    {
      original: 'heilig',
      translation: 'holy',
      diphthong: 'ei',
      audioFile: './audios/diphthongsVocabulary/heilig.mp3',
    },
    {
      original: 'neus',
      translation: 'nose',
      diphthong: 'eu',
      audioFile: './audios/diphthongsVocabulary/neus.mp3',
    },
    {
      original: 'leuk',
      translation: 'nice',
      diphthong: 'eu',
      audioFile: './audios/diphthongsVocabulary/leuk.mp3',
    },
    {
      original: 'beuk',
      translation: 'beech',
      diphthong: 'eu',
      audioFile: './audios/diphthongsVocabulary/beuk.mp3',
    },
    {
      original: 'geur',
      translation: 'scent',
      diphthong: 'eu',
      audioFile: './audios/diphthongsVocabulary/geur.mp3',
    },
    {
      original: 'keuken',
      translation: 'kitchen',
      diphthong: 'eu',
      audioFile: './audios/diphthongsVocabulary/keuken.mp3',
    },

    {
      original: 'dier',
      translation: 'animal',
      diphthong: 'ie',
      audioFile: './audios/diphthongsVocabulary/dier.mp3',
    },
    {
      original: 'mier',
      translation: 'ant',
      diphthong: 'ie',
      audioFile: './audios/diphthongsVocabulary/mier.mp3',
    },
    {
      original: 'gierig',
      translation: 'greedy',
      diphthong: 'ie',
      audioFile: './audios/diphthongsVocabulary/gierig.mp3',
    },
    {
      original: 'zwierig',
      translation: 'graceful',
      diphthong: 'ie',
      audioFile: './audios/diphthongsVocabulary/zwierig.mp3',
    },
    {
      original: 'drie',
      translation: 'three',
      diphthong: 'ie',
      audioFile: './audios/diphthongsVocabulary/drie.mp3',
    },
    {
      original: 'ijs',
      translation: 'ice cream',
      diphthong: 'ij',
      audioFile: './audios/diphthongsVocabulary/ijs.mp3',
    },
    {
      original: 'pijn',
      translation: 'pain',
      diphthong: 'ij',
      audioFile: './audios/diphthongsVocabulary/pijn.mp3',
    },
    {
      original: 'rijk',
      translation: 'rich',
      diphthong: 'ij',
      audioFile: './audios/diphthongsVocabulary/rijk.mp3',
    },
    {
      original: 'tijd',
      translation: 'time',
      diphthong: 'ij',
      audioFile: './audios/diphthongsVocabulary/tijd.mp3',
    },
    {
      original: 'wijn',
      translation: 'wine',
      diphthong: 'ij',
      audioFile: './audios/diphthongsVocabulary/wijn.mp3',
    },
    {
      original: 'vrouw',
      translation: 'woman',
      diphthong: 'ou',
      audioFile: './audios/diphthongsVocabulary/vrouw.mp3',
    },
    {
      original: 'koud',
      translation: 'cold',
      diphthong: 'ou',
      audioFile: './audios/diphthongsVocabulary/koud.mp3',
    },
    {
      original: 'fout',
      translation: 'mistake',
      diphthong: 'ou',
      audioFile: './audios/diphthongsVocabulary/fout.mp3',
    },
    {
      original: 'jouw',
      translation: 'your',
      diphthong: 'ou',
      audioFile: './audios/diphthongsVocabulary/jouw.mp3',
    },

    {
      original: 'huis',
      translation: 'house',
      diphthong: 'ui',
      audioFile: './audios/diphthongsVocabulary/huis.mp3',
    },
    {
      original: 'luid',
      translation: 'loud',
      diphthong: 'ui',
      audioFile: './audios/diphthongsVocabulary/luid.mp3',
    },
    {
      original: 'fruit',
      translation: 'fruit',
      diphthong: 'ui',
      audioFile: './audios/diphthongsVocabulary/fruit.mp3',
    },
    {
      original: 'sluit',
      translation: 'close',
      diphthong: 'ui',
      audioFile: './audios/diphthongsVocabulary/sluit.mp3',
    },
    {
      original: 'buiten',
      translation: 'outside',
      diphthong: 'ui',
      audioFile: './audios/diphthongsVocabulary/buiten.mp3',
    },
    {
      original: 'muur',
      translation: 'wall',
      diphthong: 'uu',
      audioFile: './audios/diphthongsVocabulary/muur.mp3',
    },
    {
      original: 'vuur',
      translation: 'fire',
      diphthong: 'uu',
      audioFile: './audios/diphthongsVocabulary/vuur.mp3',
    },
    {
      original: 'duur',
      translation: 'expensive',
      diphthong: 'uu',
      audioFile: './audios/diphthongsVocabulary/duur.mp3',
    },
    {
      original: 'uur',
      translation: 'hour',
      diphthong: 'uu',
      audioFile: './audios/diphthongsVocabulary/uur.mp3',
    },
    {
      original: 'kuur',
      translation: 'treatment',
      diphthong: 'uu',
      audioFile: './audios/diphthongsVocabulary/kuur.mp3',
    },
    {
      original: 'boek',
      translation: 'book',
      diphthong: 'oe',
      audioFile: './audios/diphthongsVocabulary/boek.mp3',
    },
    {
      original: 'hoed',
      translation: 'hat',
      diphthong: 'oe',
      audioFile: './audios/diphthongsVocabulary/hoed.mp3',
    },
    {
      original: 'stoel',
      translation: 'chair',
      diphthong: 'oe',
      audioFile: './audios/diphthongsVocabulary/stoel.mp3',
    },
    {
      original: 'goed',
      translation: 'good',
      diphthong: 'oe',
      audioFile: './audios/diphthongsVocabulary/goed.mp3',
    },
    {
      original: 'boer',
      translation: 'farmer',
      diphthong: 'oe',
      audioFile: './audios/diphthongsVocabulary/boer.mp3',
    },
  ],
};
